image: node:lts

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - npm install
    - npm run build  # If you have a build script, otherwise remove this line
    - pm2 start server.js --name "your-app-name"  # Adjust this line based on your process manager
  only:
    - main  # Deploy only from the main branch